/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.Serializable

/**
 * @param large
 * @param medium
 * @param small
 */
@Serializable
data class Avatar(
    val large: String,
    val medium: String,
    val small: String,
)