/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * type of a character 角色，机体，舰船，组织...
 *
 * Values: Character,Mechanic,Ship,Organization
 */
@Serializable(with = CharacterTypeSerializer::class)
enum class CharacterType(
    val value: Int,
) {
    Character(1),

    Mechanic(2),

    Ship(3),

    Organization(4),
    ;

    companion object {
        fun fromValue(value: Int): CharacterType? = CharacterType.entries.find { it.value == value }
    }
}

object CharacterTypeSerializer : KSerializer<CharacterType> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("UserGroup", PrimitiveKind.INT)

    override fun serialize(
        encoder: Encoder,
        value: CharacterType,
    ) {
        encoder.encodeInt(value.value)
    }

    override fun deserialize(decoder: Decoder): CharacterType {
        val value = decoder.decodeInt()
        return CharacterType.fromValue(value) ?: throw IllegalArgumentException("Unknown UserGroup value: $value")
    }
}