/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.Serializable

/**
 * @param error error message
 * @param path request path
 */

@Serializable
data class DetailOneOf(
    // error message
    val error: String? = null,
    // request path
    val path: String? = null,
)