/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.Detail
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param title
 * @param description
 * @param details
 */

@Serializable
data class ErrorDetail(
    val title: String,
    val description: String,
    val details: Detail? = null,
)