/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.Serializable

/**
 * @param total
 * @param limit
 * @param offset
 * @param `data`
 */

@Serializable
data class PagedUserCharacterCollection(
    val total: Int? = 0,
    val limit: Int? = 0,
    val offset: Int? = 0,
    val `data`: List<UserCharacterCollection>? = arrayListOf(),
)