/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.Serializable

/**
 * @param total
 * @param limit
 * @param offset
 */

@Serializable
data class Page(
    val total: Int,
    val limit: Int,
    val offset: Int,
)