/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.EpisodeCollectionType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param episodeId 
 * @param type 
 */


data class PatchUserSubjectEpisodeCollectionRequest (

    @Json(name = "episode_id")
    val episodeId: kotlin.collections.List<kotlin.Int>,

    @Json(name = "type")
    val type: EpisodeCollectionType

) {


}

