/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.CharacterType
import io.sakurasou.halo.bangumi.model.PersonImages
import io.sakurasou.halo.bangumi.model.SubjectType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 角色，机体，舰船，组织...
 * @param subjectId 
 * @param subjectType 
 * @param subjectName 
 * @param subjectNameCn 
 * @param images object with some size of images, this object maybe `null`
 * @param staff 
 */


data class PersonCharacter (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String,

    /* 角色，机体，舰船，组织... */
    @Json(name = "type")
    val type: CharacterType,

    @Json(name = "subject_id")
    val subjectId: kotlin.Int,

    @Json(name = "subject_type")
    val subjectType: SubjectType,

    @Json(name = "subject_name")
    val subjectName: kotlin.String,

    @Json(name = "subject_name_cn")
    val subjectNameCn: kotlin.String,

    /* object with some size of images, this object maybe `null` */
    @Json(name = "images")
    val images: PersonImages? = null,

    @Json(name = "staff")
    val staff: kotlin.String? = null

) {


}

