/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.PersonRevisionProfession
import io.sakurasou.halo.bangumi.model.RevisionExtra

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param prsnInfobox 
 * @param prsnSummary 
 * @param profession 
 * @param extra 
 * @param prsnName 
 */


data class PersonRevisionDataItem (

    @Json(name = "prsn_infobox")
    val prsnInfobox: kotlin.String,

    @Json(name = "prsn_summary")
    val prsnSummary: kotlin.String,

    @Json(name = "profession")
    val profession: PersonRevisionProfession,

    @Json(name = "extra")
    val extra: RevisionExtra,

    @Json(name = "prsn_name")
    val prsnName: kotlin.String

) {


}

