/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.CharacterType
import io.sakurasou.halo.bangumi.model.Person
import io.sakurasou.halo.bangumi.model.PersonImages

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type 角色，机体，舰船，组织...
 * @param relation 
 * @param images object with some size of images, this object maybe `null`
 * @param actors 演员列表
 */


data class RelatedCharacter (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String,

    /* 角色，机体，舰船，组织... */
    @Json(name = "type")
    val type: CharacterType,

    @Json(name = "relation")
    val relation: kotlin.String,

    /* object with some size of images, this object maybe `null` */
    @Json(name = "images")
    val images: PersonImages? = null,

    /* 演员列表 */
    @Json(name = "actors")
    val actors: kotlin.collections.List<Person>? = arrayListOf()

) {


}

