/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 不同条件之间是 `且` 的关系
 *
 * @param nsfw 无权限的用户会直接忽略此字段，不会返回 R18 角色。  默认或者 `null` 会返回包含 R18 的所有搜索结果。  `true` 只会返回 R18 角色。  `false` 只会返回非 R18 角色。 
 */


data class SearchCharactersRequestFilter (

    /* 无权限的用户会直接忽略此字段，不会返回 R18 角色。  默认或者 `null` 会返回包含 R18 的所有搜索结果。  `true` 只会返回 R18 角色。  `false` 只会返回非 R18 角色。  */
    @Json(name = "nsfw")
    val nsfw: kotlin.Boolean? = null

) {


}

