/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param id
 * @param type
 * @param name
 * @param nameCn
 * @param shortSummary 截短后的条目描述。
 * @param images
 * @param volumes 书籍条目的册数，由旧服务端从wiki中解析
 * @param eps 由旧服务端从wiki中解析，对于书籍条目为`话数`
 * @param collectionTotal 收藏人数
 * @param score 分数
 * @param rank 排名
 * @param tags 前 10 个 tag
 * @param date air date in `YYYY-MM-DD` format
 */

@Serializable
data class SlimSubject(
    val id: Int,
    val type: SubjectType,
    val name: String,
    @SerialName(value = "name_cn")
    val nameCn: String,
    // 截短后的条目描述。
    @SerialName(value = "short_summary")
    val shortSummary: String,
    val images: Images,
    // 书籍条目的册数，由旧服务端从wiki中解析
    val volumes: Int,
    // 由旧服务端从wiki中解析，对于书籍条目为`话数`
    val eps: Int,
    // 收藏人数
    @SerialName(value = "collection_total")
    val collectionTotal: Int,
    // 分数
    val score: Double,
    // 排名
    val rank: Int,
    // 前 10 个 tag
    val tags: List<Tag>,
    // air date in `YYYY-MM-DD` format
    val date: String? = null,
)