/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.SubjectAnimeCategory
import io.sakurasou.halo.bangumi.model.SubjectBookCategory
import io.sakurasou.halo.bangumi.model.SubjectGameCategory
import io.sakurasou.halo.bangumi.model.SubjectRealCategory

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 */


data class SubjectCategory (

) {


}

