/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 动画类型 - `0` 为 其他 - `1` 为 TV - `2` 为 OVA - `3` 为 Movie - `5` 为 WEB
 *
 * Values: Other,TV,OVA,Movie,WEB
 */

@JsonClass(generateAdapter = false)
enum class SubjectAnimeCategory(val value: kotlin.Int) {

    @Json(name = "0")
    Other(0),

    @Json(name = "1")
    TV(1),

    @Json(name = "2")
    OVA(2),

    @Json(name = "3")
    Movie(3),

    @Json(name = "5")
    WEB(5);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SubjectAnimeCategory) "$data" else null

        /**
         * Returns a valid [SubjectAnimeCategory] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SubjectAnimeCategory? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

