/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.Serializable

/**
 * - `1`: 想看 - `2`: 看过 - `3`: 在看 - `4`: 搁置 - `5`: 抛弃
 *
 * Values: Wish,Done,Doing,OnHold,Dropped
 */
@Serializable
enum class SubjectCollectionType(
    val value: Int,
) {
    Wish(1),

    Done(2),

    Doing(3),

    OnHold(4),

    Dropped(5),
}