/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.Serializable

/**
 * 条目类型 - `1` 为 书籍 - `2` 为 动画 - `3` 为 音乐 - `4` 为 游戏 - `6` 为 三次元  没有 `5`
 *
 * Values: Book,Anime,Music,Game,Real
 */
@Serializable
enum class SubjectType(
    val value: Int,
) {
    Book(1),

    Anime(2),

    Music(3),

    Game(4),

    Real(6),
}