/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.Serializable

/**
 * @param name
 * @param count
 */

@Serializable
data class Tag(
    val name: String,
    val count: Int,
)