/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param id
 * @param name
 * @param type 角色，机体，舰船，组织...
 * @param createdAt
 * @param images object with some size of images, this object maybe `null`
 */

@Serializable
data class UserCharacterCollection(
    val id: Int,
    val name: String,
    // 角色，机体，舰船，组织...
    val type: CharacterType,
    @SerialName("created_at")
    val createdAt: Instant,
    // object with some size of images, this object maybe `null`
    val images: PersonImages? = null,
)