/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.Serializable

/**
 * 用户组 - 1 = 管理员 - 2 = Bangumi 管理猿 - 3 = 天窗管理猿 - 4 = 禁言用户 - 5 = 禁止访问用户 - 8 = 人物管理猿 - 9 = 维基条目管理猿 - 10 = 用户 - 11 = 维基人
 *
 * Values: Admin,BangumiAdmin,DoujinAdmin,MutedUser,BlockedUser,PersonAdmin,WikiAdmin,User,WikiUser
 */
@Serializable
enum class UserGroup(
    val value: Int,
) {
    Admin(1),

    BangumiAdmin(2),

    DoujinAdmin(3),

    MutedUser(4),

    BlockedUser(5),

    PersonAdmin(8),

    WikiAdmin(9),

    User(10),

    WikiUser(11),
}