/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package io.sakurasou.halo.bangumi.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param subjectId
 * @param subjectType
 * @param rate
 * @param type
 * @param tags
 * @param epStatus
 * @param volStatus
 * @param updatedAt 本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性
 * @param `private`
 * @param comment
 * @param subject
 */

@Serializable
data class UserSubjectCollection(
    @SerialName(value = "subject_id")
    val subjectId: Int,
    @SerialName(value = "subject_type")
    val subjectType: SubjectType,
    val rate: Int,
    val type: SubjectCollectionType,
    val tags: List<String>,
    @SerialName(value = "ep_status")
    val epStatus: Int,
    @SerialName(value = "vol_status")
    val volStatus: Int,
    // 本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性
    @SerialName(value = "updated_at")
    val updatedAt: String,
    val `private`: Boolean,
    val comment: String? = null,
    val subject: SlimSubject? = null,
)