/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.Episode
import io.sakurasou.halo.bangumi.model.EpisodeCollectionType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param episode 
 * @param type 
 * @param updatedAt A int64 unix timestamp, `0` as unknown or un-recorded.
 */


data class UserEpisodeCollection (

    @Json(name = "episode")
    val episode: Episode,

    @Json(name = "type")
    val type: EpisodeCollectionType,

    /* A int64 unix timestamp, `0` as unknown or un-recorded. */
    @Json(name = "updated_at")
    val updatedAt: kotlin.Int

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

