/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.SubjectType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param staff 
 * @param name 
 * @param nameCn 
 * @param image 
 */


data class V0RelatedSubject (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "type")
    val type: SubjectType,

    @Json(name = "staff")
    val staff: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "name_cn")
    val nameCn: kotlin.String,

    @Json(name = "image")
    val image: kotlin.String? = null

) {


}

