/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.KV
import io.sakurasou.halo.bangumi.model.V

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param k 
 * @param v 
 */


data class ValueAnyOfInner (

    @Json(name = "k")
    val k: kotlin.String,

    @Json(name = "v")
    val v: kotlin.String

) {


}

