/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.GetMyself200Response
import io.sakurasou.halo.bangumi.model.Avatar
import io.sakurasou.halo.bangumi.model.UserGroup

class GetMyself200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetMyself200Response
        //val modelInstance = GetMyself200Response()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `username` - 唯一用户名，初始与 UID 相同，可修改一次
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `nickname`
        should("test nickname") {
            // uncomment below to test the property
            //modelInstance.nickname shouldBe ("TODO")
        }

        // to test the property `userGroup`
        should("test userGroup") {
            // uncomment below to test the property
            //modelInstance.userGroup shouldBe ("TODO")
        }

        // to test the property `avatar`
        should("test avatar") {
            // uncomment below to test the property
            //modelInstance.avatar shouldBe ("TODO")
        }

        // to test the property `sign` - 个人签名
        should("test sign") {
            // uncomment below to test the property
            //modelInstance.sign shouldBe ("TODO")
        }

        // to test the property `email` - 用户绑定的邮箱地址
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `regTime` - 用户注册时间。比如 2017-12-03T08:51:16+08:00
        should("test regTime") {
            // uncomment below to test the property
            //modelInstance.regTime shouldBe ("TODO")
        }

        // to test the property `timeOffset` - 用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8
        should("test timeOffset") {
            // uncomment below to test the property
            //modelInstance.timeOffset shouldBe ("TODO")
        }

    }
}
