/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.Index
import io.sakurasou.halo.bangumi.model.Creator
import io.sakurasou.halo.bangumi.model.Stat

class IndexTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Index
        //val modelInstance = Index()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `desc`
        should("test desc") {
            // uncomment below to test the property
            //modelInstance.desc shouldBe ("TODO")
        }

        // to test the property `stat` - 目录评论及收藏数
        should("test stat") {
            // uncomment below to test the property
            //modelInstance.stat shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `creator`
        should("test creator") {
            // uncomment below to test the property
            //modelInstance.creator shouldBe ("TODO")
        }

        // to test the property `ban` - deprecated, always false.
        should("test ban") {
            // uncomment below to test the property
            //modelInstance.ban shouldBe ("TODO")
        }

        // to test the property `nsfw`
        should("test nsfw") {
            // uncomment below to test the property
            //modelInstance.nsfw shouldBe ("TODO")
        }

        // to test the property `total` - 收录条目总数
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

    }
}
