/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.PersonRevisionProfession

class PersonRevisionProfessionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonRevisionProfession
        //val modelInstance = PersonRevisionProfession()

        // to test the property `producer`
        should("test producer") {
            // uncomment below to test the property
            //modelInstance.producer shouldBe ("TODO")
        }

        // to test the property `mangaka`
        should("test mangaka") {
            // uncomment below to test the property
            //modelInstance.mangaka shouldBe ("TODO")
        }

        // to test the property `artist`
        should("test artist") {
            // uncomment below to test the property
            //modelInstance.artist shouldBe ("TODO")
        }

        // to test the property `seiyu`
        should("test seiyu") {
            // uncomment below to test the property
            //modelInstance.seiyu shouldBe ("TODO")
        }

        // to test the property `writer`
        should("test writer") {
            // uncomment below to test the property
            //modelInstance.writer shouldBe ("TODO")
        }

        // to test the property `illustrator`
        should("test illustrator") {
            // uncomment below to test the property
            //modelInstance.illustrator shouldBe ("TODO")
        }

        // to test the property `actor`
        should("test actor") {
            // uncomment below to test the property
            //modelInstance.actor shouldBe ("TODO")
        }

    }
}
