/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.RelatedPerson
import io.sakurasou.halo.bangumi.model.PersonCareer
import io.sakurasou.halo.bangumi.model.PersonImages
import io.sakurasou.halo.bangumi.model.PersonType

class RelatedPersonTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RelatedPerson
        //val modelInstance = RelatedPerson()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type` - `1`, `2`, `3` 表示 `个人`, `公司`, `组合`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `career`
        should("test career") {
            // uncomment below to test the property
            //modelInstance.career shouldBe ("TODO")
        }

        // to test the property `relation`
        should("test relation") {
            // uncomment below to test the property
            //modelInstance.relation shouldBe ("TODO")
        }

        // to test the property `eps` - 参与章节/曲目
        should("test eps") {
            // uncomment below to test the property
            //modelInstance.eps shouldBe ("TODO")
        }

        // to test the property `images` - object with some size of images, this object maybe `null`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

    }
}
