/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.RelatedCharacter
import io.sakurasou.halo.bangumi.model.CharacterType
import io.sakurasou.halo.bangumi.model.Person
import io.sakurasou.halo.bangumi.model.PersonImages

class RelatedCharacterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RelatedCharacter
        //val modelInstance = RelatedCharacter()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type` - 角色，机体，舰船，组织...
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `relation`
        should("test relation") {
            // uncomment below to test the property
            //modelInstance.relation shouldBe ("TODO")
        }

        // to test the property `images` - object with some size of images, this object maybe `null`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `actors` - 演员列表
        should("test actors") {
            // uncomment below to test the property
            //modelInstance.actors shouldBe ("TODO")
        }

    }
}
