/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.SearchSubjectsRequest
import io.sakurasou.halo.bangumi.model.SearchSubjectsRequestFilter

class SearchSubjectsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchSubjectsRequest
        //val modelInstance = SearchSubjectsRequest()

        // to test the property `keyword`
        should("test keyword") {
            // uncomment below to test the property
            //modelInstance.keyword shouldBe ("TODO")
        }

        // to test the property `sort` - 排序规则  - `match` meilisearch 的默认排序，按照匹配程度 - `heat` 收藏人数 - `rank` 排名由高到低 - `score` 评分 
        should("test sort") {
            // uncomment below to test the property
            //modelInstance.sort shouldBe ("TODO")
        }

        // to test the property `filter`
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

    }
}
