/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.SearchCharactersRequestFilter

class SearchCharactersRequestFilterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchCharactersRequestFilter
        //val modelInstance = SearchCharactersRequestFilter()

        // to test the property `nsfw` - 无权限的用户会直接忽略此字段，不会返回 R18 角色。  默认或者 `null` 会返回包含 R18 的所有搜索结果。  `true` 只会返回 R18 角色。  `false` 只会返回非 R18 角色。 
        should("test nsfw") {
            // uncomment below to test the property
            //modelInstance.nsfw shouldBe ("TODO")
        }

    }
}
