/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.SlimSubject
import io.sakurasou.halo.bangumi.model.Images
import io.sakurasou.halo.bangumi.model.SubjectType
import io.sakurasou.halo.bangumi.model.Tag

class SlimSubjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SlimSubject
        //val modelInstance = SlimSubject()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `nameCn`
        should("test nameCn") {
            // uncomment below to test the property
            //modelInstance.nameCn shouldBe ("TODO")
        }

        // to test the property `shortSummary` - 截短后的条目描述。
        should("test shortSummary") {
            // uncomment below to test the property
            //modelInstance.shortSummary shouldBe ("TODO")
        }

        // to test the property `images`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `volumes` - 书籍条目的册数，由旧服务端从wiki中解析
        should("test volumes") {
            // uncomment below to test the property
            //modelInstance.volumes shouldBe ("TODO")
        }

        // to test the property `eps` - 由旧服务端从wiki中解析，对于书籍条目为`话数`
        should("test eps") {
            // uncomment below to test the property
            //modelInstance.eps shouldBe ("TODO")
        }

        // to test the property `collectionTotal` - 收藏人数
        should("test collectionTotal") {
            // uncomment below to test the property
            //modelInstance.collectionTotal shouldBe ("TODO")
        }

        // to test the property `score` - 分数
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property `rank` - 排名
        should("test rank") {
            // uncomment below to test the property
            //modelInstance.rank shouldBe ("TODO")
        }

        // to test the property `tags` - 前 10 个 tag
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `date` - air date in `YYYY-MM-DD` format
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

    }
}
