/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.Stat

class StatTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Stat
        //val modelInstance = Stat()

        // to test the property `comments`
        should("test comments") {
            // uncomment below to test the property
            //modelInstance.comments shouldBe ("TODO")
        }

        // to test the property `collects`
        should("test collects") {
            // uncomment below to test the property
            //modelInstance.collects shouldBe ("TODO")
        }

    }
}
