/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.SubjectRevisionData

class SubjectRevisionDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubjectRevisionData
        //val modelInstance = SubjectRevisionData()

        // to test the property `fieldEps`
        should("test fieldEps") {
            // uncomment below to test the property
            //modelInstance.fieldEps shouldBe ("TODO")
        }

        // to test the property `fieldInfobox`
        should("test fieldInfobox") {
            // uncomment below to test the property
            //modelInstance.fieldInfobox shouldBe ("TODO")
        }

        // to test the property `fieldSummary`
        should("test fieldSummary") {
            // uncomment below to test the property
            //modelInstance.fieldSummary shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `nameCn`
        should("test nameCn") {
            // uncomment below to test the property
            //modelInstance.nameCn shouldBe ("TODO")
        }

        // to test the property `platform`
        should("test platform") {
            // uncomment below to test the property
            //modelInstance.platform shouldBe ("TODO")
        }

        // to test the property `subjectId`
        should("test subjectId") {
            // uncomment below to test the property
            //modelInstance.subjectId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `typeId`
        should("test typeId") {
            // uncomment below to test the property
            //modelInstance.typeId shouldBe ("TODO")
        }

        // to test the property `voteField`
        should("test voteField") {
            // uncomment below to test the property
            //modelInstance.voteField shouldBe ("TODO")
        }

    }
}
