/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.UserEpisodeCollection
import io.sakurasou.halo.bangumi.model.Episode
import io.sakurasou.halo.bangumi.model.EpisodeCollectionType

class UserEpisodeCollectionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserEpisodeCollection
        //val modelInstance = UserEpisodeCollection()

        // to test the property `episode`
        should("test episode") {
            // uncomment below to test the property
            //modelInstance.episode shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `updatedAt` - A int64 unix timestamp, `0` as unknown or un-recorded.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
