/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.User
import io.sakurasou.halo.bangumi.model.Avatar
import io.sakurasou.halo.bangumi.model.UserGroup

class UserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of User
        //val modelInstance = User()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `username` - 唯一用户名，初始与 UID 相同，可修改一次
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `nickname`
        should("test nickname") {
            // uncomment below to test the property
            //modelInstance.nickname shouldBe ("TODO")
        }

        // to test the property `userGroup`
        should("test userGroup") {
            // uncomment below to test the property
            //modelInstance.userGroup shouldBe ("TODO")
        }

        // to test the property `avatar`
        should("test avatar") {
            // uncomment below to test the property
            //modelInstance.avatar shouldBe ("TODO")
        }

        // to test the property `sign` - 个人签名
        should("test sign") {
            // uncomment below to test the property
            //modelInstance.sign shouldBe ("TODO")
        }

    }
}
