/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.Value
import io.sakurasou.halo.bangumi.model.ValueAnyOfInner

class ValueTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Value
        //val modelInstance = Value()

    }
}
