/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.CharacterRevisionDataItem
import io.sakurasou.halo.bangumi.model.RevisionExtra

class CharacterRevisionDataItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CharacterRevisionDataItem
        //val modelInstance = CharacterRevisionDataItem()

        // to test the property `infobox`
        should("test infobox") {
            // uncomment below to test the property
            //modelInstance.infobox shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `extra`
        should("test extra") {
            // uncomment below to test the property
            //modelInstance.extra shouldBe ("TODO")
        }

    }
}
