/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.Collection

class CollectionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Collection
        //val modelInstance = Collection()

        // to test the property `wish`
        should("test wish") {
            // uncomment below to test the property
            //modelInstance.wish shouldBe ("TODO")
        }

        // to test the property `collect`
        should("test collect") {
            // uncomment below to test the property
            //modelInstance.collect shouldBe ("TODO")
        }

        // to test the property `doing`
        should("test doing") {
            // uncomment below to test the property
            //modelInstance.doing shouldBe ("TODO")
        }

        // to test the property `onHold`
        should("test onHold") {
            // uncomment below to test the property
            //modelInstance.onHold shouldBe ("TODO")
        }

        // to test the property `dropped`
        should("test dropped") {
            // uncomment below to test the property
            //modelInstance.dropped shouldBe ("TODO")
        }

    }
}
