/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.Count

class CountTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Count
        //val modelInstance = Count()

        // to test the property `_1`
        should("test _1") {
            // uncomment below to test the property
            //modelInstance._1 shouldBe ("TODO")
        }

        // to test the property `_2`
        should("test _2") {
            // uncomment below to test the property
            //modelInstance._2 shouldBe ("TODO")
        }

        // to test the property `_3`
        should("test _3") {
            // uncomment below to test the property
            //modelInstance._3 shouldBe ("TODO")
        }

        // to test the property `_4`
        should("test _4") {
            // uncomment below to test the property
            //modelInstance._4 shouldBe ("TODO")
        }

        // to test the property `_5`
        should("test _5") {
            // uncomment below to test the property
            //modelInstance._5 shouldBe ("TODO")
        }

        // to test the property `_6`
        should("test _6") {
            // uncomment below to test the property
            //modelInstance._6 shouldBe ("TODO")
        }

        // to test the property `_7`
        should("test _7") {
            // uncomment below to test the property
            //modelInstance._7 shouldBe ("TODO")
        }

        // to test the property `_8`
        should("test _8") {
            // uncomment below to test the property
            //modelInstance._8 shouldBe ("TODO")
        }

        // to test the property `_9`
        should("test _9") {
            // uncomment below to test the property
            //modelInstance._9 shouldBe ("TODO")
        }

        // to test the property `_10`
        should("test _10") {
            // uncomment below to test the property
            //modelInstance._10 shouldBe ("TODO")
        }

    }
}
