/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.EpisodeDetail
import io.sakurasou.halo.bangumi.model.EpType

class EpisodeDetailTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EpisodeDetail
        //val modelInstance = EpisodeDetail()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `nameCn`
        should("test nameCn") {
            // uncomment below to test the property
            //modelInstance.nameCn shouldBe ("TODO")
        }

        // to test the property `sort` - 同类条目的排序和集数
        should("test sort") {
            // uncomment below to test the property
            //modelInstance.sort shouldBe ("TODO")
        }

        // to test the property `airdate`
        should("test airdate") {
            // uncomment below to test the property
            //modelInstance.airdate shouldBe ("TODO")
        }

        // to test the property `comment`
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `duration`
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `desc` - 简介
        should("test desc") {
            // uncomment below to test the property
            //modelInstance.desc shouldBe ("TODO")
        }

        // to test the property `disc` - 音乐曲目的碟片数
        should("test disc") {
            // uncomment below to test the property
            //modelInstance.disc shouldBe ("TODO")
        }

        // to test the property `subjectId`
        should("test subjectId") {
            // uncomment below to test the property
            //modelInstance.subjectId shouldBe ("TODO")
        }

        // to test the property `ep` - 条目内的集数, 从`1`开始。非本篇剧集的此字段无意义
        should("test ep") {
            // uncomment below to test the property
            //modelInstance.ep shouldBe ("TODO")
        }

    }
}
