/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.PersonImages

class PersonImagesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonImages
        //val modelInstance = PersonImages()

        // to test the property `large`
        should("test large") {
            // uncomment below to test the property
            //modelInstance.large shouldBe ("TODO")
        }

        // to test the property `medium`
        should("test medium") {
            // uncomment below to test the property
            //modelInstance.medium shouldBe ("TODO")
        }

        // to test the property `small`
        should("test small") {
            // uncomment below to test the property
            //modelInstance.small shouldBe ("TODO")
        }

        // to test the property `grid`
        should("test grid") {
            // uncomment below to test the property
            //modelInstance.grid shouldBe ("TODO")
        }

    }
}
