/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.PersonCharacter
import io.sakurasou.halo.bangumi.model.CharacterType
import io.sakurasou.halo.bangumi.model.PersonImages
import io.sakurasou.halo.bangumi.model.SubjectType

class PersonCharacterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonCharacter
        //val modelInstance = PersonCharacter()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type` - 角色，机体，舰船，组织...
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `subjectId`
        should("test subjectId") {
            // uncomment below to test the property
            //modelInstance.subjectId shouldBe ("TODO")
        }

        // to test the property `subjectType`
        should("test subjectType") {
            // uncomment below to test the property
            //modelInstance.subjectType shouldBe ("TODO")
        }

        // to test the property `subjectName`
        should("test subjectName") {
            // uncomment below to test the property
            //modelInstance.subjectName shouldBe ("TODO")
        }

        // to test the property `subjectNameCn`
        should("test subjectNameCn") {
            // uncomment below to test the property
            //modelInstance.subjectNameCn shouldBe ("TODO")
        }

        // to test the property `images` - object with some size of images, this object maybe `null`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `staff`
        should("test staff") {
            // uncomment below to test the property
            //modelInstance.staff shouldBe ("TODO")
        }

    }
}
