/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.RevisionExtra

class RevisionExtraTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RevisionExtra
        //val modelInstance = RevisionExtra()

        // to test the property `img`
        should("test img") {
            // uncomment below to test the property
            //modelInstance.img shouldBe ("TODO")
        }

    }
}
