/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.SearchSubjectsRequestFilter
import io.sakurasou.halo.bangumi.model.SubjectType

class SearchSubjectsRequestFilterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchSubjectsRequestFilter
        //val modelInstance = SearchSubjectsRequestFilter()

        // to test the property `type` - 条目类型，参照 `SubjectType` enum，多值之间为 `或` 的关系。
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `metaTags` - 公共标签。多个值之间为 `且` 关系。可以用 `-` 排除标签。比如 `-科幻` 可以排除科幻标签。
        should("test metaTags") {
            // uncomment below to test the property
            //modelInstance.metaTags shouldBe ("TODO")
        }

        // to test the property `tag` - 标签，可以多次出现。多值之间为 `且` 关系。
        should("test tag") {
            // uncomment below to test the property
            //modelInstance.tag shouldBe ("TODO")
        }

        // to test the property `airDate` - 播出日期/发售日期，日期必需为 `YYYY-MM-DD` 格式。多值之间为 `且` 关系。
        should("test airDate") {
            // uncomment below to test the property
            //modelInstance.airDate shouldBe ("TODO")
        }

        // to test the property `rating` - 用于搜索指定评分的条目，多值之间为 `且` 关系。
        should("test rating") {
            // uncomment below to test the property
            //modelInstance.rating shouldBe ("TODO")
        }

        // to test the property `rank` - 用于搜索指定排名的条目，多值之间为 `且` 关系。
        should("test rank") {
            // uncomment below to test the property
            //modelInstance.rank shouldBe ("TODO")
        }

        // to test the property `nsfw` - 无权限的用户会直接忽略此字段，不会返回R18条目。  默认或者 `null` 会返回包含 R18 的所有搜索结果。  `true` 只会返回 R18 条目。  `false` 只会返回非 R18 条目。 
        should("test nsfw") {
            // uncomment below to test the property
            //modelInstance.nsfw shouldBe ("TODO")
        }

    }
}
