/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.SearchPersonsRequest
import io.sakurasou.halo.bangumi.model.SearchPersonsRequestFilter

class SearchPersonsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchPersonsRequest
        //val modelInstance = SearchPersonsRequest()

        // to test the property `keyword`
        should("test keyword") {
            // uncomment below to test the property
            //modelInstance.keyword shouldBe ("TODO")
        }

        // to test the property `filter`
        should("test filter") {
            // uncomment below to test the property
            //modelInstance.filter shouldBe ("TODO")
        }

    }
}
