/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.SearchPersonsRequestFilter

class SearchPersonsRequestFilterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchPersonsRequestFilter
        //val modelInstance = SearchPersonsRequestFilter()

        // to test the property `career` - 职业，可以多次出现。多值之间为 `且` 关系。
        should("test career") {
            // uncomment below to test the property
            //modelInstance.career shouldBe ("TODO")
        }

    }
}
