/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.Subject
import io.sakurasou.halo.bangumi.model.Collection
import io.sakurasou.halo.bangumi.model.Images
import io.sakurasou.halo.bangumi.model.Item
import io.sakurasou.halo.bangumi.model.Rating
import io.sakurasou.halo.bangumi.model.SubjectType
import io.sakurasou.halo.bangumi.model.Tag

class SubjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Subject
        //val modelInstance = Subject()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `nameCn`
        should("test nameCn") {
            // uncomment below to test the property
            //modelInstance.nameCn shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `series` - 是否为书籍系列的主条目
        should("test series") {
            // uncomment below to test the property
            //modelInstance.series shouldBe ("TODO")
        }

        // to test the property `nsfw`
        should("test nsfw") {
            // uncomment below to test the property
            //modelInstance.nsfw shouldBe ("TODO")
        }

        // to test the property `locked`
        should("test locked") {
            // uncomment below to test the property
            //modelInstance.locked shouldBe ("TODO")
        }

        // to test the property `platform` - TV, Web, 欧美剧, DLC...
        should("test platform") {
            // uncomment below to test the property
            //modelInstance.platform shouldBe ("TODO")
        }

        // to test the property `images`
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `volumes` - 书籍条目的册数，由旧服务端从wiki中解析
        should("test volumes") {
            // uncomment below to test the property
            //modelInstance.volumes shouldBe ("TODO")
        }

        // to test the property `eps` - 由旧服务端从wiki中解析，对于书籍条目为`话数`
        should("test eps") {
            // uncomment below to test the property
            //modelInstance.eps shouldBe ("TODO")
        }

        // to test the property `totalEpisodes` - 数据库中的章节数量
        should("test totalEpisodes") {
            // uncomment below to test the property
            //modelInstance.totalEpisodes shouldBe ("TODO")
        }

        // to test the property `rating`
        should("test rating") {
            // uncomment below to test the property
            //modelInstance.rating shouldBe ("TODO")
        }

        // to test the property `collection`
        should("test collection") {
            // uncomment below to test the property
            //modelInstance.collection shouldBe ("TODO")
        }

        // to test the property `metaTags` - 由维基人维护的 tag
        should("test metaTags") {
            // uncomment below to test the property
            //modelInstance.metaTags shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `date` - air date in `YYYY-MM-DD` format
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `infobox`
        should("test infobox") {
            // uncomment below to test the property
            //modelInstance.infobox shouldBe ("TODO")
        }

    }
}
