/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.SubjectCategory
import io.sakurasou.halo.bangumi.model.SubjectAnimeCategory
import io.sakurasou.halo.bangumi.model.SubjectBookCategory
import io.sakurasou.halo.bangumi.model.SubjectGameCategory
import io.sakurasou.halo.bangumi.model.SubjectRealCategory

class SubjectCategoryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubjectCategory
        //val modelInstance = SubjectCategory()

    }
}
