/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.UserSubjectCollection
import io.sakurasou.halo.bangumi.model.SlimSubject
import io.sakurasou.halo.bangumi.model.SubjectCollectionType
import io.sakurasou.halo.bangumi.model.SubjectType

class UserSubjectCollectionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserSubjectCollection
        //val modelInstance = UserSubjectCollection()

        // to test the property `subjectId`
        should("test subjectId") {
            // uncomment below to test the property
            //modelInstance.subjectId shouldBe ("TODO")
        }

        // to test the property `subjectType`
        should("test subjectType") {
            // uncomment below to test the property
            //modelInstance.subjectType shouldBe ("TODO")
        }

        // to test the property `rate`
        should("test rate") {
            // uncomment below to test the property
            //modelInstance.rate shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `epStatus`
        should("test epStatus") {
            // uncomment below to test the property
            //modelInstance.epStatus shouldBe ("TODO")
        }

        // to test the property `volStatus`
        should("test volStatus") {
            // uncomment below to test the property
            //modelInstance.volStatus shouldBe ("TODO")
        }

        // to test the property `updatedAt` - 本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property ``private``
        should("test `private`") {
            // uncomment below to test the property
            //modelInstance.`private` shouldBe ("TODO")
        }

        // to test the property `comment`
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

    }
}
