/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.sakurasou.halo.bangumi.model.UserSubjectCollectionModifyPayload
import io.sakurasou.halo.bangumi.model.SubjectCollectionType

class UserSubjectCollectionModifyPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserSubjectCollectionModifyPayload
        //val modelInstance = UserSubjectCollectionModifyPayload()

        // to test the property `type` - 修改条目收藏类型
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `rate` - 评分，`0` 表示删除评分
        should("test rate") {
            // uncomment below to test the property
            //modelInstance.rate shouldBe ("TODO")
        }

        // to test the property `epStatus` - 只能用于修改书籍条目进度
        should("test epStatus") {
            // uncomment below to test the property
            //modelInstance.epStatus shouldBe ("TODO")
        }

        // to test the property `volStatus` - 只能用于修改书籍条目进度
        should("test volStatus") {
            // uncomment below to test the property
            //modelInstance.volStatus shouldBe ("TODO")
        }

        // to test the property `comment` - 评价
        should("test comment") {
            // uncomment below to test the property
            //modelInstance.comment shouldBe ("TODO")
        }

        // to test the property ``private`` - 仅自己可见
        should("test `private`") {
            // uncomment below to test the property
            //modelInstance.`private` shouldBe ("TODO")
        }

        // to test the property `tags` - 不传或者 `null` 都会被忽略，传 `[]` 则会删除所有 tag。
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

    }
}
