/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.Avatar
import io.sakurasou.halo.bangumi.model.UserGroup

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param username 唯一用户名，初始与 UID 相同，可修改一次
 * @param nickname 
 * @param userGroup 
 * @param avatar 
 * @param sign 个人签名
 * @param email 用户绑定的邮箱地址
 * @param regTime 用户注册时间。比如 2017-12-03T08:51:16+08:00
 * @param timeOffset 用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8
 */


data class GetMyself200Response (

    @Json(name = "id")
    val id: kotlin.Int,

    /* 唯一用户名，初始与 UID 相同，可修改一次 */
    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "nickname")
    val nickname: kotlin.String,

    @Json(name = "user_group")
    val userGroup: UserGroup,

    @Json(name = "avatar")
    val avatar: Avatar,

    /* 个人签名 */
    @Json(name = "sign")
    val sign: kotlin.String,

    /* 用户绑定的邮箱地址 */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /* 用户注册时间。比如 2017-12-03T08:51:16+08:00 */
    @Json(name = "reg_time")
    val regTime: java.time.OffsetDateTime? = null,

    /* 用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8 */
    @Json(name = "time_offset")
    val timeOffset: kotlin.Int? = null

) {


}

