/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.PersonCareer
import io.sakurasou.halo.bangumi.model.PersonImages
import io.sakurasou.halo.bangumi.model.PersonType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param type `1`, `2`, `3` 表示 `个人`, `公司`, `组合`
 * @param career 
 * @param shortSummary 
 * @param locked 
 * @param images object with some size of images, this object maybe `null`
 */


data class Person (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "name")
    val name: kotlin.String,

    /* `1`, `2`, `3` 表示 `个人`, `公司`, `组合` */
    @Json(name = "type")
    val type: PersonType,

    @Json(name = "career")
    val career: kotlin.collections.List<PersonCareer>,

    @Json(name = "short_summary")
    val shortSummary: kotlin.String,

    @Json(name = "locked")
    val locked: kotlin.Boolean,

    /* object with some size of images, this object maybe `null` */
    @Json(name = "images")
    val images: PersonImages? = null

) {


}

