/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.SearchPersonsRequestFilter

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param keyword 
 * @param filter 
 */


data class SearchPersonsRequest (

    @Json(name = "keyword")
    val keyword: kotlin.String,

    @Json(name = "filter")
    val filter: SearchPersonsRequestFilter? = null

) {


}

