/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 不同条件之间是 `且` 的关系
 *
 * @param career 职业，可以多次出现。多值之间为 `且` 关系。
 */


data class SearchPersonsRequestFilter (

    /* 职业，可以多次出现。多值之间为 `且` 关系。 */
    @Json(name = "career")
    val career: kotlin.collections.List<kotlin.String>? = null

) {


}

