/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model

import io.sakurasou.halo.bangumi.model.Collection
import io.sakurasou.halo.bangumi.model.Images
import io.sakurasou.halo.bangumi.model.Item
import io.sakurasou.halo.bangumi.model.Rating
import io.sakurasou.halo.bangumi.model.SubjectType
import io.sakurasou.halo.bangumi.model.Tag

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param type 
 * @param name 
 * @param nameCn 
 * @param summary 
 * @param series 是否为书籍系列的主条目
 * @param nsfw 
 * @param locked 
 * @param platform TV, Web, 欧美剧, DLC...
 * @param images 
 * @param volumes 书籍条目的册数，由旧服务端从wiki中解析
 * @param eps 由旧服务端从wiki中解析，对于书籍条目为`话数`
 * @param totalEpisodes 数据库中的章节数量
 * @param rating 
 * @param collection 
 * @param metaTags 由维基人维护的 tag
 * @param tags 
 * @param date air date in `YYYY-MM-DD` format
 * @param infobox 
 */


data class Subject (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "type")
    val type: SubjectType,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "name_cn")
    val nameCn: kotlin.String,

    @Json(name = "summary")
    val summary: kotlin.String,

    /* 是否为书籍系列的主条目 */
    @Json(name = "series")
    val series: kotlin.Boolean,

    @Json(name = "nsfw")
    val nsfw: kotlin.Boolean,

    @Json(name = "locked")
    val locked: kotlin.Boolean,

    /* TV, Web, 欧美剧, DLC... */
    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "images")
    val images: Images,

    /* 书籍条目的册数，由旧服务端从wiki中解析 */
    @Json(name = "volumes")
    val volumes: kotlin.Int,

    /* 由旧服务端从wiki中解析，对于书籍条目为`话数` */
    @Json(name = "eps")
    val eps: kotlin.Int,

    /* 数据库中的章节数量 */
    @Json(name = "total_episodes")
    val totalEpisodes: kotlin.Int,

    @Json(name = "rating")
    val rating: Rating,

    @Json(name = "collection")
    val collection: Collection,

    /* 由维基人维护的 tag */
    @Json(name = "meta_tags")
    val metaTags: kotlin.collections.List<kotlin.String>,

    @Json(name = "tags")
    val tags: kotlin.collections.List<Tag>,

    /* air date in `YYYY-MM-DD` format */
    @Json(name = "date")
    val date: kotlin.String? = null,

    @Json(name = "infobox")
    val infobox: kotlin.collections.List<Item>? = null

) {


}

