/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.sakurasou.halo.bangumi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 游戏类型 - `0` 为 其他 - `4001` 为 游戏 - `4002` 为 软件 - `4003` 为 扩展包 - `4005` 为 桌游
 *
 * Values: Other,Games,Software,DLC,Tabletop
 */

@JsonClass(generateAdapter = false)
enum class SubjectGameCategory(val value: kotlin.Int) {

    @Json(name = 0)
    Other(0),

    @Json(name = 4001)
    Games(4001),

    @Json(name = 4003)
    Software(4003),

    @Json(name = 4002)
    DLC(4002),

    @Json(name = 4005)
    Tabletop(4005);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SubjectGameCategory) "$data" else null

        /**
         * Returns a valid [SubjectGameCategory] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SubjectGameCategory? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

